unit-finance/unit-node-sdk

unit.ts

adding a wildcard import to helpers in class unit introduce central point to ask for all functions and his types this let us have a well-defined typing and avoid introduce any at this point. 
TODO:
- address any comment over this PR.

expose all helpers and its specific types in class unit

---

helpers.ts

BeneficialOwner percentage should be a optional number 
TODO:
- address any comment over this PR

[helpers] change percentage type to number 

---

.gitignore

This PR improves the gitignore file by excluding some common OS and IDE artifcats

 Gitignore common OS and IDE artifacts

---

resources/index.ts
types/index.ts

add application form to resources and type indices
TODO:
address any comment over this PR

add application form to indices

---

resources/applicationForm.ts
types/applicationForm.ts

Adding missing get method for applicationForms. 
I'm not quite sure of the interface for ApplicationForm as it's not documented. I just went by the response from the API so there are a few `TODO` in the interface to fill in.

add ApplicationForm type + get method

---

types/common.ts

This PR improves handling of non-existent error data in the API response in the UnitError extraction logic

Improve UnitError extractor to handle non-existent data

---

types/common.ts

Reference the additional officer titles - https://docs.unit.co/types/#officer

Add additional officer titles

---

resources/payments.ts

https://github.com/unit-finance/unit-node-sdk/issues/69

filter[customerId]

---

resources/cards.ts
types/applicationForm.ts
types/cards.ts

https://developers.unit.co/cards/#get-pin-status

add PinStatus to sdk

---

resources/institutions.ts
types/institution.ts
unit.ts

https://docs.unit.co/institutions#get-institution-by-routingNumber
https://github.com/unit-finance/unit-node-sdk/issues/78

Institutions

---

resources/counterparty.ts
types/counterparty.ts

get counterparty balance
https://developers.unit.co/payments-counterparties/#get-counterparty-balance
https://github.com/unit-finance/unit-node-sdk/issues/76

get counterparty balance

---

resources/cards.ts
types/cards.ts

Create method to fetch card limits using https://docs.unit.co/cards#card-limits

Create method for fetching card limits

---

types/transactions.ts

added two new transactions
https://developers.unit.co/resources/#transaction-check-deposit
https://developers.unit.co/resources/#transaction-returned-check-deposit
also:
- tags changed to optional
quick question, tags in book transaction tags are supposed to be outside of attributes?
https://developers.unit.co/resources/#transaction-book

new transactions

---

resources/authorization.ts

Allow optional cardId filter when fetching authorizations using https://docs.unit.co/cards-authorizations#list-authorizations

Allow optional cardId filter when fetching authorizations

---

types/common.ts
types/events.ts

This PR improves type hierarchy for the Events resource (in the same vein as #52)

Improve type hierarchy for Events resource

---

resources/events.ts

This PR adds filter-by-type capability to the events resource.

Enable filtering by type on events resource

---

resources/application.ts
types/application.ts

https://github.com/unit-finance/unit-node-sdk/issues/86
feat: update individual and business application

feat: update application

---

resources/account.ts
types/account.ts

Freeze and unfreeze account request are added to account.ts. FreezeAccount type is also added to types. Please review my code!
Thanks

Freeze and unfreeze account requests is added to accounts

---

types/webhooks.ts

https://github.com/unit-finance/unit-node-sdk/issues/99

added deliveryMode and Json contentType to Webhooks

---

types/counterparty.ts

Export `CreateCounterpartyWithoutTokenRequest` & `CreateCounterpartyWithTokenRequest`

Export a few more types

---

resources/payments.ts
tests/payments.spec.ts

https://github.com/unit-finance/unit-node-sdk/issues/126

Cancel payment

---

types/events.ts

Add missing type definition for pending review as documented [here](https://docs.unit.co/events/#applicationpendingreview)

add typing for application.pendingReview

---

resources/application.ts
resources/webhooks.ts
types/application.ts
types/common.ts

- added few fields to create application
- added include object to create application function
- lint-fix
https://github.com/unit-finance/unit-node-sdk/issues/138

Add included to create application response

---

types/account.ts
types/counterparty.ts

added permissions to craete counterparty
added attributes to account limits

small updates

---

resources/account.ts
resources/application.ts
resources/authorization.ts
resources/authorizationRequest.ts
resources/cards.ts
resources/checkDeposit.ts
resources/counterparty.ts
resources/customer.ts
resources/events.ts
resources/payments.ts
resources/receivedPayments.ts
resources/statements.ts
resources/transactions.ts
resources/webhooks.ts
types/common.ts
types/rewards.ts

added BaseListParams interface that extends UnimplementedFields
added new filters to ListParams
every ListParams extends BaseListParams
https://github.com/unit-finance/unit-node-sdk/issues/153

New Filters

---

resources/cards.ts

Add relationship to the response from get card.

Update get card return type

---

resources/authorization.ts
tests/authorizations.spec.ts
types/authorization.ts

https://github.com/unit-finance/unit-node-sdk/issues/183

Authorizations fix

---

package-lock.json
package.json
resources/events.ts
types/authorization.ts
types/authorizationRequest.ts
types/common.ts
types/events.ts
types/payments.ts
types/transactions.ts

added new events
added new types (Direction, Merchant, HealthcareAmounts)
added sub types for events for better control of exporting UnitEvent
BaseEvent added to UnitEvent for future use in case of not supported new event, BaseEvent will be the GenericEvent
small changes:
- events list, fixed the type param
thanks to:
@[pklicnik](https://github.com/pklicnik) (https://github.com/unit-finance/unit-node-sdk/issues/178)

Support New Events

---

tests/cards.spec.ts
types/cards.ts

Fixed card limits during card creation
https://github.com/unit-finance/unit-node-sdk/issues/181

Card limits 

---

helpers.ts
types/common.ts

https://github.com/unit-finance/unit-node-sdk/issues/180
now addresses are not only in US

Global Addresses

---

resources/baseResource.ts
resources/cards.ts
resources/counterparty.ts
tests/cards.spec.ts
types/cards.ts

https://github.com/unit-finance/unit-node-sdk/issues/179
also added some changes to post and put methods.
DataPayload type

Update Card 

---

resources/applicationForm.ts
tests/applicationForms.spec.ts
tests/billPays.spec.ts
tests/receivedPayments.spec.ts

added list to ApplicationForms with tests
https://developers.unit.co/application-forms/#list-application-forms

List ApplicationForms

---

resources/recurringPayments.ts
tests/recurringPayments.spec.ts
types/recurringPayment.ts
unit.ts

Fixes #199 
https://docs.unit.co/recurring-payments#recurring-payment-credit-ach-payment

Add Create Recurring Credit ACH payment

---

resources/applicationForm.ts
types/applicationForm.ts
types/customerToken.ts

- added some missing attributes to ApplicationForm
- created ApplicationFormSettingsOverride
- added LocalizationOptions
- UnitScope - https://github.com/unit-finance/unit-node-sdk/issues/128

small update to SDK

---

tests/applications.spec.ts
tests/testHelpers.ts
types/application.ts
types/common.ts

implementation of [Trust Application](https://docs.unit.co/resources#trustapplication) with tests
added new type of application to our SDK
made some changes to all application types, made them more generic
added new types to common

Trust Application

---

resources/recurringPayments.ts
tests/recurringPayments.spec.ts
types/recurringPayment.ts

implemented the missing methods + tests
https://docs.unit.co/recurring-payments

Recurring Payment Full Support

---

helpers.ts
resources/account.ts
resources/baseResource.ts
resources/customer.ts
tests/customers.spec.ts
types/customer.ts

added add and remove authorized users, with tests.
also added archive customer

Authorized Users for Customer

---

resources/authorizationRequest.ts
types/authorizationRequest.ts
types/common.ts
types/transactions.ts

main changes:
- added new transaction, PaymentCanceledTransaction
- added PurchaseAuthorizationRequest and AtmAuthorizationRequest
small changes:
- added CardRelatedAttributes
- added id to Merchant
- added CardNetwork type
- added declineReason type
https://github.com/unit-finance/unit-node-sdk/issues/220

New transaction and new authorization requests

---

types/payments.ts

https://github.com/unit-finance/unit-node-sdk/issues/230
SameDay field
- added sameDay to CreateRequest and the ach type
- added some fields that were missing
- added BaseCreateAchPaymentAttributes

SameDay Ach payment

---

types/returns.ts

added reasons to sdk
https://docs.unit.co/ach-returns/#ach-return-reason

ACH Return Reason

---

types/institution.ts

Institution address

---

resources/cards.ts
tests/orgTokens.spec.ts
types/cards.ts

Add to mobile wallet

---

types/events.ts

- added missing event types
- now exporting all event union types

Event hooks update

---

types/customer.ts

added TrustCustomer and PatchTrustCustomerRequest

Trust Customer

---

types/cards.ts
types/events.ts

- added missing card relationship in transaction.created event
- added missing customer relationship to CreateIndividualDebitCardRequest

added missing relationships

---

resources/authorization.ts
resources/authorizationRequest.ts
types/common.ts

added list method to authorizations
added free-use param to BaseListParams
AuthorizationRequestQueryParams is exported and extends BaseListParams

ListParams and Authorizations list method

---

types/transactions.ts

Exists according to https://docs.unit.co/resources/#transaction-card
And also in a real transaction.

Add card relationship to CardTransaction

---

types/transactions.ts

- fixed issue with card transaction not showing base transaction relationships (account, customer, etc)

updated card transaction relationships

---

types/application.ts

Adds the missing application status `Canceled` as documented here: https://docs.unit.co/applications/#application-statuses

add missing application status

---

helpers.ts
resources/account.ts
tests/accounts.spec.ts
types/account.ts

- closeAccountRequest changed from class to interface
- added create close account request helper function 
- added a test for close account

Close Account - small change

---

resources/application.ts

added BeneficialOwner[] to get application included data
https://github.com/unit-finance/unit-node-sdk/issues/274

Get Application include BeneficialOwner[]

---

types/transactions.ts

The RewardTransaction is not a part of the Transaction type. If this is not intentional - please add it, as in this PR

Add RewardTransaction to the Transaction type

---

resources/application.ts
tests/applications.spec.ts
tests/testHelpers.ts
types/application.ts
types/common.ts

added create and verify document, with tests
added industry

Create and Verify Documents

---

types/common.ts

not all changes from https://github.com/unit-finance/unit-node-sdk/pull/279 were added on https://github.com/unit-finance/unit-node-sdk/pull/280.

add Always to useSelfieVerification and evaluation params to beneficial owner

---

resources/payments.ts
types/payments.ts

Unit docs: https://docs.unit.co/payments#bulk-payments
Related Issue: https://github.com/unit-finance/unit-node-sdk/issues/277

Add bulk payment create method on Payments resource

---

types/events.ts

https://github.com/unit-finance/unit-node-sdk/issues/282
https://docs.unit.co/events/#applicationcreated

new application.created event

---

types/checkDeposit.ts
types/events.ts

Fixes some incorrect types and spellings related to check deposit.
See https://docs.unit.co/resources#check-deposit

Fix some check deposit types

---

types/common.ts

AuthorizedUser was missing JwtSubject attribute

JwtSubject added to AuthorizedUser

---

helpers.ts
resources/account.ts
resources/baseResource.ts
resources/cards.ts
tests/accounts.spec.ts
tests/credits.spec.ts
tests/testHelpers.ts
types/account.ts
types/cards.ts
types/common.ts

Implemented Credit Accounts and Credit Cards 
Added tests for Credit.
https://github.com/unit-finance/unit-node-sdk/issues/297
FUTURE:
- repayments

Credit Accounts and Cards

---

tests/statements.spec.ts

Bad request for joint accounts statements

Fix statements test

---

resources/application.ts
tests/applications.spec.ts
types/application.ts

Added Cancel Application with a test
https://github.com/unit-finance/unit-node-sdk/issues/304

Cancel Application

---

types/transactions.ts

Docs: https://docs.unit.co/resources/#transaction-originatedach

Add traceNumber & secCode to originatedAchTransaction

---

README.md
types/application.ts

Updates the args for creating and updating an [Individual Application](https://docs.unit.co/applications#create-individual-application)/[Sole proprietor application]( https://docs.unit.co/applications#create-sole-proprietor-application) complying with the new "Enhanced Due Diligence" requirements. I did not make updates to the APIs for businesses.

Update args for create/update individual application

---

types/cards.ts

added defaultFundingAccount attribute to createCardRelationships and to patchCards

support defaultFundingAccount 

---

helpers.ts
resources/application.ts
resources/baseResource.ts
tests/applications.spec.ts
tests/testHelpers.ts
types/application.ts
types/applicationForm.ts
types/common.ts

added fields to Applications DTO's
added[ create-sole-proprietor-application-request](https://docs.unit.co/applications#create-sole-proprietor-application)
added all update applications requests
added update BeneficialOwner with test
added BeneficialOwnerDTO
added tests for each case and structure

Applications Update

---

tests/counterparties.spec.ts
types/counterparty.ts

updated Create Counterparty requests and added 2 tests to simulate CreateCounterparty requests

Counterparty Update Create Requests

---

resources/checkDeposit.ts
types/checkDeposit.ts

update check deposit and added confirm method

Check Deposit AwaitingCustomerConfirmation Status and Confirmation method

---

types/transactions.ts

added 3 new transactions
https://docs.unit.co/resources/#transaction-account-low-balance-closure
https://docs.unit.co/resources/#transaction-push-to-card
https://docs.unit.co/resources/#transaction-returned-check-payment

New Transactions DTO's

---

tests/payments.spec.ts
tests/testHelpers.ts
types/payments.ts
types/transactions.ts

added secCode to create payments and few more missing attributes

add secCode to createAchPayments

---

tests/payments.spec.ts
types/application.ts

update types, differ between business and soleProprietor
https://github.com/unit-finance/unit-node-sdk/issues/336

update NumberOfEmployees type

---

types/authorization.ts
types/common.ts
types/transactions.ts

[RichMerchantData and CurrencyConversion added](https://github.com/unit-finance/unit-node-sdk/commit/bf8e69972c8e65b8598d52406bbbf5e339b2bb7b)

Foreign Currency

---

types/events.ts

some new events and small changes

added new events

---

resources/statements.ts

fix sort type in list params
https://github.com/unit-finance/unit-node-sdk/issues/363

fix: Sort type in StatementsListParams

---

types/application.ts
types/applicationForm.ts
types/common.ts
types/customer.ts

https://github.com/unit-finance/unit-node-sdk/issues/367

Update Entity Type

---

.github/workflows/CI-appsec-blackduck-master.yml
.github/workflows/CI-appsec-blackduck-pr.yml

As we did with unit-web-sdk earlier, we are also integrating Black Duck into this repo. 
The initial PR check will fail, but it will pass after merging and running the scan on master.

DSO-630-blackduck-unit-node-sdk-init

---

types/payments.ts

added clearingDaysOverride field

clearingDaysOverride 

---

resources/checkPayments.ts
tests/checkPayments.spec.ts
types/checkPayment.ts
types/common.ts
types/events.ts

added create checkPayment and new events

Check Payments

---

.github/workflows/CI-appsec-blackduck-master.yml
.github/workflows/CI-appsec-blackduck-pr.yml

Synopsys team released new GitHub Action v1.5.0 to support new FixPR capability

DSO-786-GitHubActionv1.5.0-FixPRcapability

---

resources/checkPayments.ts
tests/checkPayments.spec.ts
types/checkPayment.ts

- cancel check payment
- update check payment statuses
- added a test

Cancel CheckPayment

---

tests/checkPayments.spec.ts
types/checkPayment.ts

thank to @wen-relay https://github.com/unit-finance/unit-node-sdk/issues/407
the attribute field should be 'return'

fix: ReturnCheckPayment

---

types/cards.ts

Update the CardLevelLimits interface to have optional properties

make CardLevelLimits properties optional

---

types/cards.ts

BaseUpdateAttributes limits type

---

resources/simulations.ts
types/simulations.ts

added Authorization Requests Simulations

Authorization Requests simulations

---

tests/orgTokens.spec.ts
types/orgToken.ts

added resources to CreateApiToken

CreateApiToken with Resources

---

types/recurringPayment.ts

added dayOfWeek to BaseSchedule

Weekly Schedule

---

resources/baseResource.ts
resources/cashDeposits.ts
tests/cashDeposits.spec.ts
types/cashDeposit.ts
unit.ts

implementation of Cash Deposits with tests
https://www.unit.co/docs/api/payments/cash-deposits/

feat: Cash Deposits

---

resources/receivedPayments.ts
types/payments.ts

https://github.com/unit-finance/unit-node-sdk/issues/441

patch received payment

---

resources/simulations.ts

This matches [the Unit docs linked here.](https://unit.co/docs/api/simulations-cards/#simulate-activate-card)
I've tested this in my sandbox environment and confirmed it works 👍

Add activate card simulation

---

resources/cards.ts
types/cards.ts

Fixing a typo around `CardCreationRequest`

Fix typo on Card Creation Request Type

---

tests/accounts.spec.ts
types/account.ts

credit and deposit account limits with a test

refactoring: Account Limits

---

resources/recurringRepayments.ts
tests/recurringRepayments.spec.ts
tests/repayments.spec.ts
tests/testHelpers.ts
types/baseRepaymentTypes.ts
types/common.ts
types/recurringPayment.ts
types/recurringRepayments.ts
types/repayments.ts
unit.ts

**Changes**
- Refactored types around repayments
- Added recurring repayments
- Added recurring repayements related tests

Recurring repayments

---

resources/baseResource.ts
tests/applicationForms.spec.ts
tests/applications.spec.ts
types/applicationForm.ts
types/common.ts

**Changes**
- Added new base header for Unit client name X-Accept-Version
- Updated relationships for Create Application Form

New base headers x-accept-version and relationships update for Create Application Form

---

resources/transactions.ts

https://www.unit.co/docs/api/transactions/#query-parameters-1

Add accountType to transactions#list params

---

resources/migrations.ts
tests/migrations.spec.ts
types/migration.ts
unit.ts

**Changes**
- Added migrations find endpoint and created the related test

Migrations find endpoint

---

package-lock.json
package.json
types/migration.ts

**Changes**
- Fixed migration status incorrect naming
- Bump to 1.0.1

Fixed migration status incorrect naming, bump to 1.0.1

---

types/transactions.ts

https://www.unit.co/docs/api/resources/#transaction-wire

Wire transaction description is optional

---

resources/simulations.ts
types/simulations.ts

I can confirm this works in sandbox

Add transmit ACH payment simulation

---

package-lock.json
package.json
resources/simulations.ts
tests/orgTokens.spec.ts
types/simulations.ts

**Changes**
- Added clear ach payment
- Fixed clear ach payment simulation
- Version bump to 1.2.1
Original PR https://github.com/unit-finance/unit-node-sdk/pull/494

Clear ach payment and version bump to 1.2.1

---

package-lock.json
package.json
resources/counterparty.ts
tests/applications.spec.ts
tests/counterparties.spec.ts
tests/creditApplications.spec.ts
types/applicationForm.ts

**Changes**
- Added application relationship to form v2
- Version bump to 1.2.4
- Test fixes

Add application to V2 application form relationships 

---

types/transactions.ts

https://www.unit.co/docs/api/resources/#transaction-returned-check-payment

Add `returnedCheckPaymentTransaction`

---

resources/receivedPayments.ts

https://www.unit.co/docs/api/received-ach/#reprocess-received-payment

Add `ReceivedPayments.reprocess` endpoint
