- unit.ts
Users of the client should be able to provide a `basePath` with a trailing slash.
The following are examples of how this will transform incoming `basePath` inputs: 
- `https://api.s.unit.sh` ⟶ `https://api.s.unit.sh`
- `https://api.s.unit.sh/` ⟶ `https://api.s.unit.sh`
- `https://api.s.unit.sh////` ⟶ `https://api.s.unit.sh`
One minor issue one may have with this implementation is that it's generally [considered bad practice to modify input arguments in the function body](https://stackoverflow.com/a/41260819), but in this case the author favored brevity over convention.
> Remove trailing slashes from user-provided basePath

- resources/account.ts
- resources/application.ts
- resources/applicationForm.ts
- resources/authorization.ts
- resources/baseResource.ts
- resources/batchAccounts.ts
- resources/cards.ts
- resources/counterparty.ts
- resources/customer.ts
- resources/customerToken.ts
- resources/events.ts
- resources/fee.ts
- resources/payments.ts
- resources/statements.ts
- resources/transactions.ts
- resources/webhooks.ts
- types/common.ts
- unit.ts
This may be a controversial idea, so please bear with me ...
At first glance, this seems like a bad idea, since it breaks encapsulation by leaking an API client implementation detail to the outside world. One of the several downsides of breaking encapsulation is that it may make it difficult to transparently migrate to a different http client (e.g. [got](https://github.com/sindresorhus/got)) in the future.
In the wild, we see several examples of API clients allowing users to provide their own instance of axios:
- [Segment's API client](https://github.com/segmentio/analytics-node/blob/3ec3f4212bfd4cc22f8bbe67dda13f337b7bb484/index.js#L41)
- [Plaid's new API client](https://github.com/plaid/plaid-node/blob/578c4e9f067fb1f76257c549829f5dc2d6e8e973/dist/base.js#L40) 
The reason this is done …
> Enable users to inject custom Axios instance

- resources/baseResource.ts
- types/common.ts
- unit.ts
This PR converts the `UnitError` object to a subclass of the Error object. 
While it is possible in JS to throw anything, it is generally considered bad practice. Please see discussions on [this stackoverflow thread](https://stackoverflow.com/a/11512623):  
> - Catching code may expect the thrown object to have the usual message, stacktrace, and name properties that appear on Errors.
> - Lack of a stacktrace makes debugging problematic, especially in the case of uncaught exceptions / unhandled rejections. E.g. Debugging an "Uncaught [Object object]" error can be particularly painful.
>
> Throw subclass of Error instead of POJSO

- types/customer.ts
The [API json schema](https://docs.unit.co/#json-schema) released on Unit's documentation site describes the customer type values are camel cased but the current client implementation documents it in pascal case.
> Convert customer type enum to camel case

- types/application.ts
- types/customer.ts
The unit API makes use of union types in its responses. The client currently handles exposing these types incositently:  
- Certain types make use of the [union types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#union-types) typescript feature, e.g. [Accounts](https://github.com/unit-finance/unit-node-sdk/blob/main/types/account.ts), [Payments](https://github.com/unit-finance/unit-node-sdk/blob/main/types/payments.ts), [Transactions](https://github.com/unit-finance/unit-node-sdk/blob/main/types/transactions.ts):
* [Accounts](https://github.com/unit-finance/unit-node-sdk/blob/main/types/account.ts): `export type Account = DepositAccount | BatchAccount`
* [Payments](https://github.com/unit-finance/unit-node-sdk/blob/main/types/payments.ts): `export type Payment = …
> Convert application and customer DTOs into unions of sibling interfaces

- resources/account.ts
- resources/application.ts
- resources/applicationForm.ts
- resources/authorization.ts
- resources/authorizationRequest.ts
- resources/baseResource.ts
- resources/batchAccounts.ts
- resources/cards.ts
- resources/counterparty.ts
- resources/customer.ts
- resources/customerToken.ts
- resources/events.ts
- resources/fee.ts
- resources/payments.ts
- resources/returns.ts
- resources/statements.ts
- resources/transactions.ts
- resources/webhooks.ts
- unit.ts
Currently, all resource functions are annotated with the return type `Promise<UnitError | T>`, but these functions never resolve the promise with an object of type `UnitError`, only with objects of type `T`. 
This PR removes `UnitError` from the return type annotation of resource functions. This was done since it's ergonomically frustrating to consume these functions in typescript, where after every invocation, I have to do a pointless assertion that the response is `!isUnitError` to appease the compiler that the response is indeed of type `T`. 
I suspect this is an artifact from a time when this implementation returned the UnitError instead of throwing it. 
There are two options to resolve this concern: 
1. (**proposed**) Keep the exception-based control flow for handling non-2xx …
> Remove UnitError from resource return types

- resources/account.ts
- resources/cards.ts
- types/cards.ts
The return types on the Accounts#list and Cards#list operations were not array types. Which should be the expected return types for clients based on Unit's SDK. See: 
* https://docs.unit.co/#list-deposit-accounts
* https://docs.unit.co/#list-cards
> Fixed return types on list Cards and list Accounts

- resources/transactions.ts
I noticed my tests were failing in our app after switching to the SDK. This was the culprit.
> fix typo in params

- types/customerToken.ts
See: https://docs.unit.co/#customers-create-customer-bearer-token
> Added missing field `expiresIn` to `customerTokenRequest`

- resources/accountEndOfDay.ts
- types/accountEndOfDay.ts
- unit.ts
Changes
- added `AccountsEndOfDay` class with the following method:
- `list(params: AccountEndOfDayParams): Promise<UnitResponse<AccountEndOfDay[]> & Include<Customer> & Include<Account> & Include<Customer[]>>` 
- added `AccountsEndOfDay` interface with values and descriptions from unit docs: `https://docs.unit.co/resources#account-end-of-day`
> add AccountEndOfDay class + types

- resources/transactions.ts
This fix a small bug with transactions where the update is not working because the request does not been inside a data field as it is described here https://docs.unit.co/#update-transaction.
TODOs:
- Address any future comment over this PR
> [Fix update transaction] make request been nested inside a data field 

- types/events.ts
- types/payments.ts
- types/transactions.ts
It seems that `direction` is always either "Credit" or "Debit", correct?
> use union type for direction

- types/application.ts
On the Application resource, there exists an ApplicationForm relation that can be used to link end users that create an ApplicationForm with the resulting Application.  This is important for the CustomerCreated event which only has the Application resource as a relation.
This change aligns the Application type with the exposed Relationship with ApplicationForm
https://docs.unit.co/resources#relationships
https://docs.unit.co/resources#relationships-1
> add optional applicationForm to application type

- types/webhooks.ts
Fix the typings of `CreateWebhookRequest` - the `token` is optional in the API.
> Fix `CreateWebhookRequest`: optional `token`

- types/events.ts
add missing typing for `account.reopened`, `account.frozen` and `account.unfrozen` as defined in the [api specification](https://docs.unit.co/events#accountreopened).
> add typing for account events

- types/authorization.ts
`card` relationship not supported in the return type for authorization but is a response from the Unit api - https://docs.unit.co/resources#authorization
> Support for card relationship in authorization

- types/transactions.ts
Thir PR contains:
- new [Payment Advance Transaction](https://developers.unit.co/resources#transaction-payment-advance)
- new [Repaid Payment Advance Transaction](https://developers.unit.co/resources#transaction-repaid-payment-advance)
- few changes to existed transactions
> Payment Advance  and Repaid Payment Advance Transactions

- types/transactions.ts
Both SDK documentation and API specification notes it as optional, see https://docs.unit.co/resources#transaction-originatedach
> fix(types): make OriginatedAchTransaction.addenda optional

- resources/baseResource.ts
- types/common.ts
Allow the setting of the User-Agent header to be configurable. This allows us to use this SDK on the browser without having User-Agent errors pop up in console.
> Make setting User-Agent optional

- types/events.ts
Currently, the `UnitEvent` type is hard to work with because of the inheritance pattern from the current `BaseEvent` type. Because it defines a `type: string` the compiler is unable to effectively narrow the type when matching on the string literal for an event type, I.e.: 
```
const parseEvent = (event: UnitEvent): unknown => {
if (event.type === 'account.closed') {
const narrowedEvent: AccountClosed | BaseEvent = event;
return narrowedEvent.attributes.closeReason;  // unknown
}
};
```
By removing `BaseEvent`  from the union of possible events (`UnitEvent`), checking the type for the appropriate string literal will instead narrow to the correct type:
```
const parseEvent = (event: UnitEvent) => {
if (event.type === 'account.closed') {
const narrowedEvent: AccountClosed = event;
return …
```
> Change `Event` type hierarchy for better Typescript support

- types/authorization.ts
This PR correctly reflects the relationship object on the authorization resource as documented [here](https://docs.unit.co/resources#authorization).
> Correct available authorization relationships on response

- resources/receivedPayments.ts
- types/events.ts
- types/payments.ts
This PR
- Corrects the return type for ReceivedPayments.list() by adding the pagination object
- Improves type-safety for keys referring to received payments status strings
> Improve types for received ACH payments resource

- resources/authorizationRequest.ts
- types/authorizationRequest.ts
Add optional attributes to `ApproveAuthorizationRequest` to support selecting a `fundingAccount` to be used for funding the `Card Purchase Transaction`
Relevant API docs:
https://docs.unit.co/cards-authorization-requests#approve-authorization-request
> Add fundingAccount and tags attributes on ApproveAuthorizationRequest

- resources/recurringPayments.ts
We were getting an error from the API saying that we weren't
providing the correct Content-Type. However, we were generating
the request from the SDK so we stepped through how the request
was being created on the SDK-side of things and found that the
headers were being stripped from within Axios:
https://github.com/axios/axios/blob/649d739288c8e2c55829ac60e2345a0f3439c730/dist/axios.js#L1449-L1450
After some discussion, the correct solution would be to update
the API to not require a Content-Type header whenever there is
no body since it's not necessary, and is a waste of bytes over
the wire.
The current patch to the SDK is a temporary fix until we remove
the restriction from the API.
Full context: https://highbeamco.slack.com/archives/C02JB5M1599/p1660766477125359
> Pass an empty body for enable/disable recurring payments

- types/payments.ts
- types/recurringPayment.ts
> Recurring Credit Book - small fix

- types/recurringPayment.ts
In the Unit docs for [creating a recurring ACH payment](https://docs.unit.co/recurring-payments/#recurring-payment-credit-ach-payment) and [creating a recurring book payment](https://docs.unit.co/recurring-payments/#recurring-credit-book-payment), `counterparty` and `counterpartyAccount` are listed as required fields under `Relationships`. However, currently these properties are nullable. 
This PR makes a small update to ensure recurring payments (both `RecurringCreditAchPayment` and `RecurringCreditBookPayment`) require a counterparty by removing nullability on these fields. This makes sense logically as having a recurring payment without a counterparty is an invalid state. 
This is the same requirement for the `AchPayment` and `BookPayment` Payment types.
> Remove `counterparty` nullability for `RecurringCreditAchPayment` and `RecurringCreditBookPayment`

- resources/cards.ts
- types/cards.ts
With the new partner **Astra** the new endpoint added to api, which is `Enable Card To Card Payments Using Astra`.
Also regarding documentation following link may be helpful: 
https://guides.unit.co/partnerships/astra/#enable-card-to-card-payments-using-astra
Since it is mentioned in guides section it may not be seen before but it is a working endpoint.
> Enable to card to card payment is implemented

- types/events.ts
According to [docs](https://docs.unit.co/events/#transactioncreated), `balance` and `available` properties are also included in the event (they also are when looking at what is sent to us).
> add missing properties in transaction.created event

- resources/batchAccounts.ts
Related PR https://github.com/unit-finance/unit-node-sdk/pull/276
Batch Releases accept an array of requests per docs: https://docs.unit.co/batch-payments#create-batch-releases
This PR changes the BatchRelease `create` method parameter/return types so they are consistent with the docs
> Send batch release with array of requests

- types/authorization.ts
According to the Unit docs for the [authorization resource](https://docs.unit.co/resources/#authorization) there are many optional attributes such as `summary` and `tags`. These attributes are currently missing in the Unit Node SDK typing for the authorization resource, so I added them with this PR.
Most of the added attributes were taken from the `CardRelatedTransactionsBaseAttributes` type.
> Update authorization attribute types to match docs

- types/events.ts
We encountered an issue when consuming webhooks from Unit with this SDK. The current type definition of `AuthorizationRequestPending` does not include `surcharge` in its `attributes`. Copied to the bottom of this description is a payload we received recently where there is a surcharge included with the authorization request (with some info replaced with dots since this a public repo).
Notably, I believe `internationalServiceFee` is also missing from the type definition and could be something that we'd want as well given that this would incur additional costs that we would be worried about. However, I leave that from the scope of this PR as I am trying to address a very narrow issue.
```
{
"data": {
"id": ".......",
"type": "authorizationRequest.pending",
"attributes": {
"createdAt": …
```
> Add surcharge to AuthorizationRequestPending type definition

- package.json
- resources/simulations.ts
- tsconfig.build.json
- types/simulations.ts
This adds support for the [Receive ACH payment simulation](https://docs.unit.co/simulations/#simulate-receive-ach-payment) This is different from the (already supported, and confusingly similarly named) [Create ACH Received Payment](https://docs.unit.co/simulations/#simulate-ach-received-payment) 
This PR has two commits because it's stacked on top of [my other PR](https://github.com/unit-finance/unit-node-sdk/pull/355) If that one gets merged in, I can reduce this down to just one commit.
> Add support for receive ACH payment simulation

- resources/simulations.ts
- types/simulations.ts
This adds support for the simulation endpoint shown in the docs here: https://docs.unit.co/simulations#simulate-card-purchase
I also edited the actual payload to better line up with the docs. I made a bunch of fields optional.
> Add support for create transaction simulation

- resources/transactions.ts
- types/transactions.ts
Fix bugged url in `update` which didn't allow for updating book or chargeback transactions due to incorrect url
[https://docs.unit.co/transactions#update-transaction-tags](url)
[https://docs.unit.co/transactions#update-book-transaction](url)
[https://docs.unit.co/transactions#update-chargeback-transaction](url)
> function to update book/chargeback transactions

- resources/simulations.ts
- types/simulations.ts
- types/transactions.ts
This has 2 commits because I'm using it on top of [my other PR](https://github.com/unit-finance/unit-node-sdk/pull/381).
If the other PR gets merged in I can rebase this so it just shows one commit.
I have confirmed in production that this `authorization` relationship can be present. [It's also shown in the docs.](https://docs.unit.co/resources/#transaction-card)
> Add optional authorization relationship to CardTransaction type

- types/common.ts
Added `name` and optional `website` to the types so they [line up with the Unit docs](https://docs.unit.co/types#rich-merchant-data)
> Add name and website to rich merchant type

- types/transactions.ts
Added the optional `cardNetwork` field to line up ATM Transaction with [the Unit docs](https://docs.unit.co/resources/#transaction-atm)
> Add atm transaction card network

- types/common.ts
field is also missing from the Unit Docs: https://docs.unit.co/about-jsonapi/#intro-errors
> Add unit error payload meta field existingIds

- resources/statements.ts
This just matches the format for `getBankVerification` found in this same file.
I also edited `getBinary` so it just calls the `get` method with `responseEncoding = "binary"`. Reducing duplicate code!
> Allow different response encodings for get statements

- resources/statements.ts
get statement pdf/html API can have language passed in as parameter -- be it `es` or `en` for spanish / english. let's expose this in the `statements.ts` file to let folks get statements either on spanish or english. 
adding an optional `language` parameter which defaults to `en` and passes it as a parameter to the this.httpGet call .
https://docs.unit.co/statements#get-statement-pdf 
noticed this was suggested from https://github.com/unit-finance/unit-node-sdk/pull/107 over a year ago. would be great to  add as a non breaking change before changing to a parameters dict in the call.
> expose language in get statement api endpoint 

- types/events.ts
1 line change.
The [declined properties](https://docs.unit.co/events#authorizationdeclined) are all the same as [authorization created in the docs](https://docs.unit.co/events/#authorizationcreated) except there is another `reason: string`
So this PR just copy/pastes the merchant attributes from the authorization created event right above.
> Adjust authorization declined event properties so they line up with the Unit docs

- types/transactions.ts
Adding `BankRepaymentTransaction` to the list of `Transaction` types based on the following response from Unit's API:
```
{
"type": "bankRepaymentTransaction",
"id": "5557104",
"attributes": {
"createdAt": "2023-10-11T06:56:00.045Z",
"paidForDate": "231010",
"amount": 1100,
"direction": "Debit",
"balance": 5016582,
"summary": "Bank repayment from 1560118 to 1560116 for day 2023-10-10"
},
"relationships": {
"account": {
"data": {
"type": "account",
"id": "1560118"
}
},
"customer": {
"data": {
"type": "customer",
"id": "1104057"
}
},
"customers": {
"data": [
{
"type": "customer",
"id": "1104057"
}
]
},
"org": {
"data": {
"type": "org",
"id": "403"
}
},
"receivingAccount": {
"data": {
"type": "account",
"id": "1560116"
}
}
}
}
```
Basically this PR is using existing transaction types …
> Adding BankRepaymentTransaction type

- package-lock.json
- package.json
- resources/baseResource.ts
Upgrades `axios` and `semver` to versions that do not have security vulnerabilities.
In the case of `axios` I had to change  the `AxiosRequestHeaders` type to be a `RawAxiosRequestHeaders` since you technically can't / shouldn't just instantiate a new `AxiosRequestHeaders` object. Functionality should be the same, but please run tests (I wasn't able to get the tests to run properly even before making any changes).
In the case of `semver` I just ran `npm audit fix` and it bumped the version of `semver` by one revision
> Upgrade `axios` and `semver` versions

- types/dispute.ts
The `Dispute` object is missing the `link` and `disputeType` fields despite these being received from our Unit payloads. 
https://docs.unit.co/resources#dispute
> Add missing link and disputeType fields to Dispute object

- types/events.ts
- I believe the relationships for `dispute events` were accidentally copied over for `repayment events`. 
- This PR simply updates `RepaymentStatusChanged` event to have the correct relationships.
|From current SDK| From Docs|
|--|--|
|![Screenshot 2023-12-11 at 2 16 07 PM](https://github.com/unit-finance/unit-node-sdk/assets/9409848/7537235e-2d80-483d-98a6-a4fab15c54ac)|![Screenshot 2023-12-11 at 2 21 13 PM](https://github.com/unit-finance/unit-node-sdk/assets/9409848/db876312-5015-4790-a0ab-29370684c864)|
> Update relationships for RepaymentStatusChanged Event

- types/common.ts
State should be required for US addresses. Updated type to account for this.
> Update state to be required for US addresses

- resources/atmLocations.ts
- tests/atmLocations.spec.ts
- types/common.ts
Because of the changes axios made, we should use JSON.stringify when sending objects as params
thanks: @Physicliar
https://github.com/unit-finance/unit-node-sdk/issues/435
> fix: Search ATM locations

- types/customer.ts
As indicated in the [document](https://www.unit.co/docs/api/customers/#update-business-customer), we should be able to update a `dba` field for a `businessCustomer`. However, the SDK does not yet support this field in the `PatchBusinessCustomerRequest'`interface.
I have also verified that the API does indeed allow dba to be updated for a `businessCustomer`
> Support dba as an optional field to PatchBusinessCustomerRequest

- types/transactions.ts
This adds the type for checkPaymentTransaction, which is found here in the Unit docs https://www.unit.co/docs/api/resources/#transaction-check-payment
> Add check payment transaction type

- types/rewards.ts
The description says optional but the return field is not - was this a typo or intended? 
Feel free to take this over.
> Make rejectReason optional

- types/events.ts
Just added one field to match the [payload in the Unit docs](https://www.unit.co/docs/api/events/#transactionupdated)
> Add gross interchange to transaction.updated type

- types/events.ts
These match what I've seen returned from the Unit API and from the docs https://www.unit.co/docs/api/events/#paymentcreated
```
{
id: '32564793',
type: 'payment.created',
attributes: {
createdAt: '2024-08-30T23:41:34.526Z',
status: 'Pending',
amount: 1000,
direction: 'Debit',
tags: {}
},
relationships: {
payment: { data: { id: '5191197', type: 'payment' } },
account: { data: { id: '4091231', type: 'account' } },
customer: { data: { id: '2321226', type: 'customer' } }
}
}
```
> Add fields to payment created event

- package-lock.json
- package.json
- resources/receivedPayments.ts
- tests/applications.spec.ts
- tests/statements.spec.ts
- tests/testHelpers.ts
- types/payments.ts
- types/transactions.ts
**Changes**
- Including following PRs:
- https://github.com/unit-finance/unit-node-sdk/pull/514
- https://github.com/unit-finance/unit-node-sdk/pull/515
- https://github.com/unit-finance/unit-node-sdk/pull/516
- https://github.com/unit-finance/unit-node-sdk/pull/517
- https://github.com/unit-finance/unit-node-sdk/pull/518
- Test fixes
- Version bump to 1.3.3
> Version 1.3.3

- types/transactions.ts
https://www.unit.co/docs/api/resources/#transaction-returnedwire
> Add `returnedWireTransaction`

- types/payments.ts
`PendingReview` and `MarkedForReturn` were missing.
https://www.unit.co/docs/api/resources/#ach-received-payment
> Add `ReceivedPaymentStatus` types

- types/transactions.ts
This is a real field that I encountered on a production payload. Adding the type here.
> Add auth typing to atm transactions

- types/application.ts
This PR adds the `archived` type to the document types to help developers identify and filter out archived documents when working with Unit's API.
When pulling documents from Unit, archived documents are being listed alongside active documents, which can lead to duplicate documents with different statuses. Previously, there was no way to identify archived documents as the `archived` type was not defined in the types.
Added the `archived` type to the document types, making it clear to developers that this type exists and can be used for filtering.
- Developers can now identify archived documents
- Prevents confusion with duplicate documents
- Enables proper filtering of archived documents when needed
> Fix: add archived property to ApplicationDocument interface
